### PR TITLE
Adds basic symbols to each colour palette.

### PR DESCRIPTION
**Pull request by jaymeh**
I've added in a number of different symbols to each item. I've tried to go through and pull out some of the symbols that look similar to others.

I have a separate text file with the remaining symbols that were not used (there's 128 left).

Let me know if any of them need to be removed.

#12 

Thanks

### CODE REVIEW

**Comment by maxcleme** [comment]
Adding a new field to raw field would be the generation. As state [here](https://github.com/maxcleme/beadcolors/issues/12), I don't we should modify raw files for this.

**Comment by jaymeh** [comment]
Ok, so all of the changes should be done via the `go` code under the generation folder? How would you suggest this is done? A big array or some kind of external file. You'll have to bear with me as this will be the first time I'll be writing and working with `Go` code. 😄

**Comment by maxcleme** [comment]
@jaymeh That was exactly why I share my concerned about the affectation [here](https://github.com/maxcleme/beadifier/issues/24#issuecomment-645183282). IMO that's the hardest part, once we figured out a way to affect symbols to colors while maintaining consistency, writing the go code is going to be trivial and of course I could help you.

**Comment by jaymeh** [comment]
Ahh, see I misinterpreted this. You are right, generation should be used rather than tying everything directly to each CSV.

I'm going to close this PR and rethink the symbols approach, since the addition of Diamond Dots and mini perlers have meant we have run out of usable symbols. 🤔 

I was at least hoping this wouldn't happen for a while (not 4 days). 😂

**Pull request closed without merging**
